### PR TITLE
Cookies

### PR DESCRIPTION
**Pull request by danikp**
cookies missed support for domain, secure and http_only options. Added across all bridges.

set_cookie/5 deprecated in favor of new set_cookie/4 (but still exported for compatibility) 
 replaced to_cookie_expire/1 with simple_bridge_util:make_expires_from_seconds/1

### CODE REVIEW

**Comment by stuart-thackray** [comment]
Thanks danikp; I would also like this functionality to be added.

**Comment by choptastic** [comment]
Thanks Dmitry! I haven't had a chance to even look at this today, but I
will check it out over the weekend and give it a merge if all looks okay!

-Jesse

On Fri, Oct 30, 2015 at 4:37 AM, stuart-thackray <notifications@github.com>
wrote:

> Thanks danikp; I would also like this functionality to be added.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nitrogen/simple_bridge/pull/53#issuecomment-152473461>
> .
>



-- 
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by choptastic** [comment]
Looks good. Merged.

**Comment by choptastic** [comment]
Turns out there are some issues caused by this commit (giving a case clause
with {secure
, false}), so I've got this in a "cookies" branch until I get to the bottom
of the problem.

-Jesse
--
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by danikp** [comment]
Just passed over all APIs for each server. Put attention that only Yaws expects for secure and http_only instead of {secure, boolean()} and {http_only, boolean()}
http://yaws.hyber.org/yman.yaws?page=yaws_api

I will look around how o fix it.

btw, it's a good case, while #49  could help by running tests on each travis build.

**Comment by choptastic** [comment]
So late, but I've finally merged this, with a number of fixes into master branch. I'm going to give this a bit before I tag a new version, just to make sure things are stable. I've added a basic test to ensure cookies work, and it passes with all webservers.

Thanks again for submitting this, and sorry it took so long to merge into mainline.

**Pull request merged**
