### PR TITLE
Correctly convert 'undefined' to list and binary (i.e convert at all)

### PR DESCRIPTION
**Pull request by brigadier**

### CODE REVIEW

**Comment by brigadier** [comment]
Though I'm not sure if these changes are enough - there's some suspictious code for headers as well.

**Comment by choptastic** [comment]
I appreciate the pull request, but I'm not super keen on redefining to_binary and to_list to treat the atom 'undefined' as special.

Perhaps a maybe_to_list and maybe_to_binary might be the solution.

Whaddya think?

**Comment by brigadier** [comment]
K, I'll do new pull tomorrow, with maybe_to_list. 
I think the `maybe_` functions should be used in `normalize_param`, `find_param`, `find_param_group`?
Can `Body` in `request_body` possible be `undefined`?

**Comment by brigadier** [comment]
https://github.com/nitrogen/simple_bridge/pull/58

**Pull request closed without merging**
